POST http://localhost:8000/process/
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="0001.exr"

< ./test_data/0001.exr
--boundary--
